# Generated by Django 3.1.7 on 2021-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210326_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='kategori',
            new_name='category',
        ),
    ]
