# Generated by Django 3.1.7 on 2021-03-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210326_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='kategori',
        ),
    ]
