# Generated by Django 3.1.7 on 2021-04-02 04:23

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210401_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles'),
        ),
        migrations.AlterField(
            model_name='post',
            name='konten',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
